### ISSUE TITLE
Windows error: cannot open NUL

### ISSUE THREAD

**Issue by snoyberg** [hspec/silently#7]
I've only seen this recently, so I think it may be an interaction with newer GHCs. Running the following on Windows and GHC 8.6.5 fails:

```haskell
#!/usr/bin/env stack
-- stack --resolver lts-13.28 script
import System.IO.Silently

main :: IO ()
main = silence $ pure ()
```

Error message:

```
Main.hs: NUL: openFile: does not exist (No such file or directory)
```

This does not occur with GHC 8.2.2. Still testing on 8.4.4.

By seeming complete happenstance, I [merged a PR](https://github.com/fpco/typed-process/pull/24) recently which instead uses `\\.\NUL`. I can test that out next and open a PR.

**Comment by snoyberg** [comment]
Confirmed that it does not error on GHC 8.4.4.

**Comment by andreasabel** [comment]
Presumably fixed by:
- #8
